version: "2"
services:

  TRreact:
    container_name: "TRreactProd"
    command: npm run build

  TRnginx:
    container_name: "TRnginxProd"
    ports:
      - "443:443"
    volumes:
      - ./nginx.production.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/var/www/teemaderegister-react/dist
      - ../teemaderegister-be/data/uploads:/var/www/teemaderegister-be/data/uploads
      - /etc/letsencrypt:/etc/letsencrypt
